"""initial_schema

Revision ID: 0eb3abc19ec0
Revises: 
Create Date: 2026-05-28 10:03:20.469164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb3abc19ec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('bit_rate', sa.BigInteger(), nullable=True),
    sa.Column('nb_frames', sa.Integer(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('analysis_task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_project_id'), 'clips', ['project_id'], unique=False)
    op.create_table('timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('clip_count', sa.Integer(), nullable=True),
    sa.Column('xml_export_path', sa.String(length=1024), nullable=True),
    sa.Column('edl_export_path', sa.String(length=1024), nullable=True),
    sa.Column('otio_export_path', sa.String(length=1024), nullable=True),
    sa.Column('generation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_project_id'), 'timelines', ['project_id'], unique=False)
    op.create_table('clip_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('shake_score', sa.Float(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('audio_score', sa.Float(), nullable=True),
    sa.Column('is_blurry', sa.Boolean(), nullable=False),
    sa.Column('is_shaky', sa.Boolean(), nullable=False),
    sa.Column('is_overexposed', sa.Boolean(), nullable=False),
    sa.Column('is_underexposed', sa.Boolean(), nullable=False),
    sa.Column('has_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_clip_id', sa.String(length=36), nullable=True),
    sa.Column('usable_ranges', sa.JSON(), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('scenes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_segments', sa.JSON(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=256), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_duration_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id')
    )
    op.create_table('clip_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_path', sa.String(length=1024), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_chunks_clip_id'), 'clip_chunks', ['clip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_chunks_clip_id'), table_name='clip_chunks')
    op.drop_table('clip_chunks')
    op.drop_table('clip_analyses')
    op.drop_index(op.f('ix_timelines_project_id'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('ix_clips_project_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_table('projects')
    # ### end Alembic commands ###
