"""add trimmed and render paths

Revision ID: 91f79ad92341
Revises: 0eb3abc19ec0
Create Date: 2026-05-28 12:53:56.142766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f79ad92341'
down_revision: Union[str, None] = '0eb3abc19ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('trimmed_file_path', sa.String(length=1024), nullable=True))
    op.add_column('timelines', sa.Column('render_video_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timelines', 'render_video_path')
    op.drop_column('clips', 'trimmed_file_path')
    # ### end Alembic commands ###
